# Generated by Django 5.2.5 on 2025-08-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailRequest',
        ),
    ]
